clone_depth: 50

# Needed to build Cython
os: Visual Studio 2015


environment:
  matrix:
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"
      CIBW_SKIP: cp27-* cp33-* cp34-* cp35-*
      CIBW_TEST_REQUIRES: pytest
      CIBW_TEST_COMMAND: python -m pytest {project} --doctest-modules


platform:
    - x64


build_script:
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - SET MKL_NUM_THREADS=1
  - SET NUMEXPR_NUM_THREADS=1
  - SET OMP_NUM_THREADS=1
  - SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda config --set always_yes yes
  - conda update conda --quiet
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install wheel
  - pip install --upgrade cibuildwheel


test_script:
- pytest KDEpy --doctest-modules --doctest-glob="*.rst" --capture=sys


after_test:
  - cmd: "echo [pypi] > %USERPROFILE%\\.pypirc"
  - "echo username: tommyod >> %USERPROFILE%\\.pypirc"
  - "echo password: %TWINE_PASSWORD% >> %USERPROFILE%\\.pypirc"
  - python setup.py bdist_wheel


on_success:
  - ps: |
       if ($env:APPVEYOR_REPO_TAG -eq 'false' -or $env:APPVEYOR_REPO_TAG -eq 'False') {
         pip install twine
         python -m cibuildwheel --output-dir wheelhouse
         twine upload wheelhouse\\*.whl --skip-existing
          }


artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  # this directory is not deleted
  - path: wheelhouse\*
