skip_tags: true
clone_depth: 50

os: Visual Studio 2015

environment:
  matrix:
    - PY_MAJOR_VER: 3
      PYTHON_ARCH: "x86_64"
      CIBW_SKIP: cp27-* cp33-* cp34-* cp35-*

platform:
    - x64

build_script:
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - SET MKL_NUM_THREADS=1
  - SET NUMEXPR_NUM_THREADS=1
  - SET OMP_NUM_THREADS=1
  - SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda config --set always_yes yes
  - conda update conda --quiet
  - pip install wheel
  - pip install -r requirements.txt
  - pip install --upgrade cibuildwheel
  - touch .cibuildwheel
  - python setup.py develop
  - python -m cibuildwheel --output-dir wheelhouse

test_script:
- pytest --doctest-modules -v --doctest-glob="*.rst" --capture=sys
- pytest KDEpy --doctest-modules --capture=sys


artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*


after_test:
  - cmd: "echo [pypi] > %USERPROFILE%\\.pypirc"
  - cmd: "echo username: tommyod >> %USERPROFILE%\\.pypirc"
  - cmd: "echo password: %TWINE_PASSWORD% >> %USERPROFILE%\\.pypirc"
  - python setup.py bdist_wheel

on_success:
- pip install twine
- "twine upload dist\\*.whl --skip-existing"
- "twine upload wheelhouse\\*.whl --skip-existing"
