language: python

notifications:
  email: false

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      env: PIP=pip


env:
  global:
    CIBW_SKIP="cp27-* cp33-* cp34-* cp35-*"

python:
- '3.6'
before_install:
- python --version
- "$PIP install -r requirements.txt"
- "$PIP install pep8>=1.7.1"
- "$PIP install flake8>=3.5.0"
- "$PIP install twine"
- "$PIP install cibuildwheel"

install:
  - python setup.py develop
before_script:
- flake8 --show-source --ignore=F811,W293,W391,W292,W291 --max-line-length=79 --exclude="*examples.py,
  *kde.py" KDEpy
script:
- cibuildwheel --output-dir wheelhouse
- pytest KDEpy --doctest-modules --doctest-glob="*.rst" --capture=sys
- python setup.py sdist
- twine upload dist/* -u tommyod -p $TWINE_PASSWORD --skip-existing
- twine upload wheelhouse/* -u tommyod -p $TWINE_PASSWORD --skip-existing
