language: python

notifications:
  email: false

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      env: PIP=pip

python:
- '3.6'
before_install:
- python --version
- "$PIP install pep8>=1.7.1"
- "$PIP install flake8>=3.5.0"
- "$PIP install numpy>=1.14.2"
- "$PIP install scipy>=1.0.1"
- "$PIP install pytest>=3.6.2"
- "$PIP install cython>=0.28.4"
- "$PIP install matplotlib>=2.2.2"
- "$PIP install twine"
- "$PIP install cibuildwheel"

install:
  - python setup.py develop
before_script:
- flake8 --show-source --ignore=F811,W293,W391,W292,W291 --max-line-length=79 --exclude="*examples.py,
  *kde.py" KDEpy
script:
- cibuildwheel --output-dir wheelhouse
- echo 'pytest KDEpy --doctest-modules --capture=sys'
- python setup.py sdist
- twine upload dist/* -u tommyod -p $TWINE_PASSWORD --skip-existing
