language: python

notifications:
  email: false

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      python: '3.6'
      env: PIP=pip
           PYTHON=python

    - os: linux
      sudo: required
      services: docker
      python: '3.7'
      env: PIP=pip
           PYTHON=python

    - os: osx
      language: generic
      env: PIP=pip3
           PYTHON=python3


env:
  global:
    CIBW_SKIP="cp27-* cp33-* cp34-* cp35-*"

before_install:
# The default version on OSX is 2.7 - this installs python 3.7 as python3
- if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
    brew update;
    brew upgrade python;
  fi
- "$PYTHON --version"
- "$PIP install -r requirements.txt"
- "$PIP install pep8>=1.7.1"
- "$PIP install flake8>=3.5.0"

install:
- "$PYTHON setup.py develop sdist"
- "$PYTHON -m pytest KDEpy --doctest-modules --capture=sys"
before_script:
- $PYTHON -m flake8 --show-source --ignore=F811,W293,W391,W292,W291 --max-line-length=79 --exclude="*examples.py,
  *kde.py" KDEpy
script:
#- "$PIP install twine"
- "$PIP install cibuildwheel"
- "$PYTHON -m cibuildwheel --output-dir wheelhouse"
- "$PIP install twine"
- "$PYTHON -m twine upload dist/* -u tommyod -p $TWINE_PASSWORD --skip-existing"
- "$PYTHON -m twine upload wheelhouse/* -u tommyod -p $TWINE_PASSWORD --skip-existing"
