language: python

notifications:
  email: false

# The matrix expands to 3 builds.
# - OSX and linux to build wheels for these operating systems
# - py36 and py37 for general testing (linux)
# For more information about building wheels, see:
# https://pythonwheels.com/
# https://github.com/joerick/cibuildwheel

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      python: '3.6'

    - os: linux
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required
      services: docker
      python: '3.7'

    - os: osx

# The global environments are for the cibuildwheel python package
env:
  global:
    - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-*"
    - PIP=pip3
    - PYTHON=python3

before_install:
# The default version on OSX is 2.7 - this installs python 3.7 as python3
- if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
    brew update;
    brew upgrade python;
  fi
- "$PYTHON --version"
- "$PIP install -r requirements.txt"
- "$PIP install pep8>=1.7.1"
- "$PIP install flake8>=3.5.0"

install:
- "$PYTHON setup.py develop sdist"
- "$PYTHON -m pytest KDEpy --doctest-modules --capture=sys"

before_script:
- $PYTHON -m flake8 --show-source --ignore=F811,W293,W391,W292,W291 --max-line-length=79 --exclude="*examples.py,
  *kde.py" KDEpy

# If a tag was used, build wheels and deply to pypi
script:
- if [ "${TRAVIS_TAG:-}" != "" ]; then
      $PIP install cibuildwheel;
      $PYTHON -m cibuildwheel --output-dir wheelhouse;
      $PIP install twine;
      $PYTHON -m twine upload dist/* -u tommyod -p $TWINE_PASSWORD --skip-existing;
      $PYTHON -m twine upload wheelhouse/* -u tommyod -p $TWINE_PASSWORD --skip-existing;
  fi
