language: python

notifications:
  email: false

matrix:
  include:
  #  - os: linux
  #    sudo: required
  #    services: docker
  #    env: PIP=pip

    - os: osx
      language: generic
      env: PIP=pip3
           PYTHON=python3


env:
  global:
    CIBW_SKIP="cp27-* cp33-* cp34-* cp35-*"

python:
- '3.6'
before_install:
- python --version
- if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
    brew update;
    brew upgrade python;
  fi
- python --version
- "$PYTHON --version"
- "$PIP install numpy>=1.14.2"
- "$PIP install scipy>=1.0.1"
- "$PIP install pytest>=3.6.2"
- "$PIP install cython>=0.28.4"
- "$PIP install matplotlib>=2.2.2"
- "$PIP install pep8>=1.7.1"
- "$PIP install flake8>=3.5.0"
- "$PYTHON -m pytest KDEpy --doctest-modules --capture=sys"
- "$PYTHON setup.py sdist"

install:
  - "$PYTHON setup.py develop"
before_script:
- $PYTHON -m flake8 --show-source --ignore=F811,W293,W391,W292,W291 --max-line-length=79 --exclude="*examples.py,
  *kde.py" KDEpy
script:
#- "$PIP install twine"
- "$PIP install cibuildwheel"
- "$PYTHON -m cibuildwheel --output-dir wheelhouse"
- "$PYTHON -m twine upload dist/* -u tommyod -p $TWINE_PASSWORD --skip-existing"
- "$PYTHON -m twine upload wheelhouse/* -u tommyod -p $TWINE_PASSWORD --skip-existing"
