language: python
matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           PIP=pip
      install:
        - docker pull $DOCKER_IMAGE
        - python setup.py develop

    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
           PRE_CMD=linux32
           PIP=pip
      install:
        - docker pull $DOCKER_IMAGE
        - python setup.py develop

    - os: osx
      language: generic
      env: PIP=pip2
notifications:
  email: false
env:
  global:
  - TWINE_USERNAME=tommyod
python:
- '3.6'
before_install:
- "$PIP install pep8"
- "$PIP install flake8>=3.5.0"
- "$PIP install numpy>=1.14.2"
- "$PIP install scipy>=1.0.1"
- "$PIP install pytest>=3.6.2"
- "$PIP install cython>=0.28.4"
- "$PIP install matplotlib>=2.2.2"
- "$PIP install auditwheel"

before_script:
- flake8 --show-source --ignore=F811,W293,W391,W292,W291 --max-line-length=79 --exclude="*examples.py,
  *kde.py" KDEpy
script:
- pwd
deploy:
  provider: pypi
  user: tommyod
  password:
    secure: TWz68NpFZRZuduywHVHmRcdizB2+JtTUzts02X+H9AzJ+4GBosGwmjkr4ltvCsEJCdQs3SKOwgt9DJwcJlMQOVp9xcuMiBpJJ2R0XRURDUFbsFRrczLGN4XgRwWlUQOkRe3N0cTdrSVq3CRgbtz4UYYWtmNv6AyHtc5wcWzpT2NvY1RmTkxmct/kO8HDBMrvGZJjNerVYxlDC6FPziPnjEcmeN3VaYGAlIjIC7+u2JF2ZBM+DL6u36BrAN97u3K8HS2Dr/pROehbu9+yktG3bH8HklkgCbGE0vF4eav5rhv2EdgZO80Ld0Ek0pRGp1t7APJLeHjrehc7+niSqlNJYRu8eH3w6l3Kp8iCzmD4vNG16CwTDcJQpeANmrUAH6J+9NjIcfZ2idLhP5AAoNVg8wm8t2OB21EUzJ/T/SRcmqcPCq4SCnNNJxybpXv96gqC94xqWUu849hckFrqUKDLTMHudMTXZ/z0Xyn0pkS305muo77eclzdvQhTa4ww4nCG1jZi9a61IUtfTbrlRqpPR0aGG1KMddJ60dYdG4geRmCHa8Xj80M/s9WH8AnSx2LExk4UixCuq0zZDCYTIQC3YZPTrhInwsX9OwQi9mcjXCb6pCS6IcObS6c2TNbUwJyhnetCxjEl8tngRpnI9v+psrwN5bGAwyeX6G2XOKwwpSg=
  on:
    tags: false
  distributions: sdist
