language: python
notifications:
  email: false
python:
  - '3.6'
before_install:
  - pip install pep8
  - pip install flake8
  - pip install cython
install:
  - python setup.py develop
before_script:
  - flake8 --show-source --ignore=F811,W293,W391,W292,W291 --max-line-length=79 KDEpy
script:
  - pytest --doctest-modules -v --doctest-glob="*.rst" --capture=sys
deploy:
  provider: pypi
  user: tommyod
  password:
    secure: QBWqi7xXIbDiTETu7+owv31B3AFPQ8FxK8rEkNFWvtQce4oWQQ70tEbh2uP9Pz+skxbLqW6w3I4/JofJgHPaSOmDn9YEj3kJF8odPbYNX231Qo5tNRmwtHr/GIBDk+a0Hk0oS1VjuJ48JBT2Uq3KI+4Kmxsyl1tJbho67SjIKTb3CtsGemz/O3ifEjYrQYxkl4BhpqgoIZUh/Nb2Vsyfa+d4PuxMq4XbbNYuHpb7B1DbHAAsqy8MkMQQJNpQU5xNTTlCeD0SLmhlWiMbtLdQ8bv+VrnWxYvESo00BxA4wRnlObwwx6eTAvVWQOfVCMAxCnw+Pa17h4pOLkJGNgaGJmHL38mLBb46M4s5Qw95mM2GOCCpo24b/nTFvvRHuJxGoWQAcoauz4NBcIlml+YzbDl9BwyMAnCcrO/JRlkYEOFQWnVrPttXHf9qCd0X9iRtFZ/RRbijFkoz505aWmHjoCNtaXopHGdHSNZPreHr8IF16yfCSutww0KszhwurXHdyh8JjKSFkkv8Kr+V826bNEgYC1AECMIAHfqws16ZgXczXRNhityXbNOEVp2S3jGZ/yA6zsSQehzlBOTSV6odlo58lhQqN5JMhW3AjosaJFtOt2tBEFqvb+KEins636PFXp+q2D6y5PjWRlQQsJuS9BNy+Xa63RSs1ZCUo1oVeRw=
  on:
    tags: true
  distributions: "sdist bdist_wheel"
