env:
  global:
  # websockets only works on Python >= 3.4.
    - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-*"


matrix:
  include:
    - language: python
      sudo: required
      python: "3.6"
      services:
        - docker


before_install:
# Python 3 is needed to run cibuildwheel for websockets.
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      brew update;
      brew upgrade python;
    fi
# Install cibuildwheel using pip3 to make sure Python 3 is used.
  - pip3 install --upgrade cibuildwheel
# Create file '.cibuildwheel' so that extension build is not optional (c.f. setup.py).
  - touch .cibuildwheel


install:
- python --version
- "pip3 install pep8>=1.7.1"
- "pip3 install flake8>=3.5.0"
- "pip3 install numpy>=1.14.2"
- "pip3 install scipy>=1.0.1"
- "pip3 install pytest>=3.6.2"
- "pip3 install cython>=0.28.4"
- "pip3 install matplotlib>=2.2.2"
- python setup.py develop


script:
  - cibuildwheel --output-dir wheelhouse
# Upload to PyPI on tags
  - if [ "${TRAVIS_TAG:-}" != "" ]; then
      pip3 install twine;
      python3 -m twine upload --skip-existing wheelhouse/*;
fi
